### ISSUE TITLE
Glith in prerequisite.py

### ISSUE THREAD

**Issue by bonfus** [electronic-structure/SIRIUS#290]
`prerequisite.py` fails on the `xc` case.

```
python prerequisite.py $HOME/local xc
Installation prefix: /users/bonfap/local
Traceback (most recent call last):
  File "prerequisite.py", line 140, in <module>
    main()
  File "prerequisite.py", line 137, in main
    configure_package(pkg, prefix)
  File "prerequisite.py", line 76, in configure_package
    tf = tarfile.open("./libs/" + local_file_name)
  File "/usr/lib64/python2.7/tarfile.py", line 1680, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

Renaming `libxc-4.2.3.tar.gz` to `xc-4.2.3.tar.gz` solves the problem.

**Comment by toxa81** [comment]
I can't reproduce the error. On my mac I have:
```
CC=gcc-mp-7 CXX=gcc-mp-7 FC=gfortran-mp-7 FCCPP=cpp-mp-7 python prerequisite.py $HOME/local xc
Installation prefix: /Users/antonk/local
Downloading http://www.tddft.org/programs/octopus/down.php?file=libxc/4.2.3/libxc-4.2.3.tar.gz
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
```
and the library is downloaded correctly. On the other hand 
```
The requested URL /programs/octopus/download/libxc/4.2.3/xc-4.2.3.tar.gz was not found on this server.
```

**Comment by toxa81** [comment]
Ah! I know, the ./libs directory was not created
```
mkdir libs
python prerequisite.py $HOME/local xc
```
will work

**Comment by bonfus** [comment]
Yes, sorry, works for me too. Wild guess, it must have been a strange manifestation of my home directory getting close to the quota.

**Comment by toxa81** [comment]
Good!
